### ISSUE TITLE
Pinhole intrinsic calibration for stereo_centre

### ISSUE THREAD

**Issue by jimaldon** [dbarnes/radar-robotcar-dataset-sdk#2]
Regarding bumblebee, I noticed https://github.com/ori-mrg/robotcar-dataset-sdk/tree/master/models only has Pinhole intrinsic calibration for stereo_narrow_left. stereo_narrow_right, stereo_wide_left, stereo_wide_right.
However, the camera images are stored as stereo/left stereo/right and stereo/centre.

What about the intrinsics of stereo/centre? Also, which ones of the two stereo_narrow_.txt or stereo_wide_.txt are valid for stereo/left and stereo/right images?

**Comment by dbarnes** [comment]
Hi @jimaldon,

Thanks for your interest in the Dataset!

As detailed on page 4 -> Intrinsics in the original Oxford RobotCar Dataset paper:
https://robotcar-dataset.robots.ox.ac.uk/images/robotcar_ijrr.pdf

`stereo_narrow_<left/right>.txt` are for the the `stereo/centre` and `stereo/right` images.
`stereo_wide_<left/right>.txt` are for the the `stereo/left` and `stereo/right` images.

If you have any other issues with that sdk please could you file them on the individual repository and @mttgdd or I will be able to help you further. (https://github.com/ori-mrg/robotcar-dataset-sdk) 

Cheers

**Comment by jimaldon** [comment]
Great, thanks! Quick related question while we're still on this issue (I'll take further questions to the other repo :) )

So are there two intrinsic calibrations for `stereo/right` (`stereo_narrow_right.txt` and `stereo_wide_right.txt`)? What about intrinsic info for treating `stereo/right` as a monocular camera?

If for instance I feed images from one of these lenses to a visual odometry algorithm that works on monocular images, which  `Pinhole fx fy cx cy`values would be correct?

**Comment by dbarnes** [comment]
To be helpful to other users who might also ask this question please could you repost this question on the main repo and I'll close this issue. 

Thanks

**Comment by jimaldon** [comment]
Sure!
